### ISSUE TITLE
Actualizar diagrama de E-R

### ISSUE THREAD

**Issue by VRVG1** [Pedro-Nicolas-Rios-Vargas/SGC#1]
En la entidad Maestros se tendria que eliminar Carrera
En la relacion Genera se tendria que mover Fecha_Generacion a la entidad Reportes y cambiarle el nombre por Fecha_Entrega @RexTime007 
Adios y gracias humanos.

**Comment by RexTime007** [comment]
Fixed using Mermeid.

**Comment by Pedro-Nicolas-Rios-Vargas** [comment]
> Fixed using Mermeid.

Changes added in [1e88d8](https://github.com/Pedro-Nicolas-Rios-Vargas/SGC/commit/1e88d8869c99b8728e2b12042929bc2499dd04c9)
